/**
 * Flat-config migration of the old `.eslintrc.json`.
 *
 * ESLint 9 removed support for legacy `.eslintrc.*` files — every
 * project must ship `eslint.config.(js|mjs|cjs)`. We still depend on
 * `next/core-web-vitals` + `next/typescript`, which are authored in
 * the legacy preset format, so we bridge via `FlatCompat` from
 * `@eslint/eslintrc`. Once `eslint-config-next` publishes a
 * native-flat release, this file collapses to a direct import.
 */
import { FlatCompat } from "@eslint/eslintrc";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({ baseDirectory: __dirname });

// Named export then default so `import/no-anonymous-default-export`
// stays happy — the old `export default [...]` was flagged as an
// anonymous array export, which hurt tooling that introspects the
// config.
const eslintConfig = [
  // Next.js shared presets (translated from legacy `extends`).
  ...compat.extends("next/core-web-vitals", "next/typescript"),

  // Codebase-wide rule adjustments. As of Session 9 all `no-explicit-any`
  // usages were cleaned up to proper types (`unknown`, `Record<…>`, or
  // inline interfaces), so the rule is now "warn" by default and the
  // `lint:eslint` script enforces `--max-warnings=0` — any new `any`
  // surfaces as a PR-blocking warning. Revisit this posture only if
  // a new integration brings back large amounts of untyped data.
  {
    rules: {
      // Keep as warning (not error) so contributors iterating locally
      // aren't blocked mid-edit; `--max-warnings=0` in the script
      // makes CI strict without making the editor hostile.
      "@typescript-eslint/no-explicit-any": "warn",
      // A handful of admin navigation uses `<a href="/admin/…">` for
      // legit reasons (preserves cross-origin behaviour when embedded,
      // lets share-links work). Surface as warning; migrate to
      // `<Link>` case-by-case when it actually matters.
      "@next/next/no-html-link-for-pages": "warn",
      // Accept underscore-prefixed args + destructured vars as
      // intentionally-unused (Playwright's `_config` convention,
      // FastAPI-style `_req` handlers, test destructuring shims).
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },

  // CommonJS test helpers (contract scripts, check_* hooks) are
  // deliberately `.cjs` and use `require()`. The TS preset's
  // `no-require-imports` rule would otherwise flag every single one.
  {
    files: ["**/*.cjs"],
    rules: {
      "@typescript-eslint/no-require-imports": "off",
    },
  },

  // Global ignores — same entries as the old `ignorePatterns` block
  // plus the build/test artefact directories we never want linted.
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "playwright-report/**",
      "test-results/**",
      "e2e/.run-state.json",
      "e2e/.auth/**",
      // Auto-generated by Next.js — contains the triple-slash
      // reference we can't lint against.
      "next-env.d.ts",
    ],
  },
];

export default eslintConfig;
